### ISSUE TITLE
コードレビュー by vv

### ISSUE THREAD

**Issue by vvakame** [asada0701/NoughtsAndCrosses2#6]
* READMEの表記壊れてる
* コードフォーマットかけてる？
  * VisualStudioCodeのコードフォーマッタの場合使うとdiffが生じる
* es moduleの場合 'use strict'; は不要
* ファイル名的に app.js が処理の始まりかなーと思ったらそうでもなさそうだった…
  * 循環参照はめんどくさいのだ… どういう順番でファイルロードが行われるかを人間が把握して制御することは不可能に近い
  * 頂点のファイルを1つ決めて、そのファイルはどこからも参照されない構造にしたほうがよい
    * 頂点のファイルのimportが全て終わった時点で他のファイルの初期処理は全て終わっている構造
* ファイル名があまりJSっぽくない
  * Board.js -> board.js とかかなー
* `export const setCpu = (cpuLevel) => {` は普通に `export function setCpu(cpuLevel) {` でいいと思う
  * モジュールのトップレベルの関数定義には普通にfunctionを使おう
  * hoisting とかでぐぐれ
* モジュールの変数に状態を持ってるの微妙
  * 複数のゲームを同時進行させるとかができなさそう(状態が1個しか持てない
  * ゲームのリセットがめんどくさそう
* SquareBoardの `this.DEFAULT = 0;` が何のデフォルト値かわからずコメントも書いてない
* isAlreadyPutとかputで `choice` をnumberで取ってるの、不便そう
  * 普通に x, y を取れば楽なのでは？
* `const defaultScore = -1;` 定数は DEFAULT_SCORE とかにする気なのかと思ったらなんか不揃いだ
* `board.copyGameBoardArray` とかはあまりしないで直でデータアクセスでもいいかな…
  * JSの場合だとデータをキッチリ守るのは大変なのでJavaに比べると比較的ガバガバで紳士協定って感じだ
  * もしくはgetterを定義して普通のプロパティっぽく見せかける
* HumanPlayer で boardId という変数があるけどこれはなんぞや？
* HumanPlayerの中に `cpu.selectByCpu();` があるのは役割がおかしいと思う

**Comment by asada0701** [comment]
- [ ] READMEの表記壊れてる
- [ ] コードフォーマットかけてる？
VisualStudioCodeのコードフォーマッタの場合使うとdiffが生じる
- [ ] es moduleの場合 'use strict'; は不要
- [ ] ファイル名的に app.js が処理の始まりかなーと思ったらそうでもなさそうだった…
循環参照はめんどくさいのだ… どういう順番でファイルロードが行われるかを人間が把握して制御することは不可能に近い
頂点のファイルを1つ決めて、そのファイルはどこからも参照されない構造にしたほうがよい
頂点のファイルのimportが全て終わった時点で他のファイルの初期処理は全て終わっている構造
- [ ] ファイル名があまりJSっぽくない
Board.js -> board.js とかかなー
- [ ] export const setCpu = (cpuLevel) => { は普通に export function setCpu(cpuLevel) { でいいと思う
モジュールのトップレベルの関数定義には普通にfunctionを使おう
hoisting とかでぐぐれ
- [ ] モジュールの変数に状態を持ってるの微妙
複数のゲームを同時進行させるとかができなさそう(状態が1個しか持てない
ゲームのリセットがめんどくさそう
- [ ] SquareBoardの this.DEFAULT = 0; が何のデフォルト値かわからずコメントも書いてない
- [ ] isAlreadyPutとかputで choice をnumberで取ってるの、不便そう
普通に x, y を取れば楽なのでは？
- [ ] const defaultScore = -1; 定数は DEFAULT_SCORE とかにする気なのかと思ったらなんか不揃いだ
board.copyGameBoardArray とかはあまりしないで直でデータアクセスでもいいかな…
JSの場合だとデータをキッチリ守るのは大変なのでJavaに比べると比較的ガバガバで紳士協定って感じだ
もしくはgetterを定義して普通のプロパティっぽく見せかける
- [ ] HumanPlayer で boardId という変数があるけどこれはなんぞや？
- [ ] HumanPlayerの中に cpu.selectByCpu(); があるのは役割がおかしいと思う

**Comment by asada0701** [comment]
- [ ] 全体的に名前が良くない

**Comment by asada0701** [comment]
巻き上げ(hoisting)
`catName('Tiger');
function catName(name){
     console.log(`My cats name is ${name}`);
}`
